version: 0.0
os: linux

files:
  - source: ./target/ROOT.war
    destination: /opt/tomcat8/webapps
  - source: ./cloudwatch-config.json
    destination: /home/ubuntu/

hooks:
  ApplicationStop:
    - location: ./codedeploy/applicationStop.sh
      timeout: 180
      runas: ubuntu
  AfterInstall:
  - location: ./codedeploy/afterInstall.sh
    timeout: 180
    runas: ubuntu
  ApplicationStart:
  - location: ./codedeploy/applicationStart.sh
    timeout: 180
    runas: ubuntu
  BeforeInstall:
  - location: ./codedeploy/beforeInstall.sh
    timeout: 180
    runas: ubuntu