---
version: 2
jobs:
  pr_check:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: maven
    steps:
    - checkout #check out source code
    - run:
        name: Install packages
        command: sudo apt-get update && sudo apt-get install -y zip && sudo apt-get install -y python-pip && sudo pip install awscli && aws --version
    - run:
        name: maven build
        command: mvn clean install test && pwd && ls -al && ls -al target/
    - run:
        name: Build deployment artifact
        command: mkdir codedeploy_artifact &&
                 zip -r csye6225-webapp-${CIRCLE_BUILD_NUM}.zip target/ROOT.war codedeploy/*.sh appspec.yml &&
                 pwd && ls -al && mv csye6225-webapp-${CIRCLE_BUILD_NUM}.zip codedeploy_artifact/ &&
                 ls -al && pwd && cd codedeploy_artifact && pwd && ls -al && cd .. && pwd && ls -al
    - run: 
        name: Copy artifact to S3
        command: aws s3 sync ./codedeploy_artifact s3://${S3_CODEDEPLOY_BUCKET}

  build_deploy:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: maven
    steps:
    - checkout #check out source code
    - run:
        name: Install packages
        command: sudo apt-get update &&
                 sudo apt-get install -y python-pip &&
                 sudo pip install awscli
    - run:
        name: maven build
        command: mvn clean install test && pwd && ls -al && ls -al target/
    
workflows:
  version: 2
  pr-check-workflow:
    jobs:
    - pr_check
  build-deploy-workflow:
    jobs:
    - build_deploy:
        filters:
          branches:
            only: feature/assignment7